#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

import argparse
import os

import sh

from save import Save
from fix import Fix

import argcomplete as argcomplete

PRJDIR = os.path.dirname(os.path.realpath(__file__))
DEF_CONF = os.path.join(os.environ['HOME'], '.config', 'config-disp', 'default.conf')

parser = argparse.ArgumentParser()
parser.add_argument('--config', type=str,
                    default=DEF_CONF,
                    help='config file path (default: ' + DEF_CONF + ')')

subparsers = parser.add_subparsers()
subparsers.required = True
subparsers.dest = "command"

Save(subparsers)
Fix(subparsers)

if 'argcomplete' in globals():
    argcomplete.autocomplete(parser)

args = parser.parse_args()
args.displayplacer = sh.Command(os.path.join(PRJDIR, "displayplacer", "displayplacer"))

args.func(args)

